custom:
    login-url: test-login
    credencials:
        user: test-user
        password: pass
spring:
    application:
        name: piotry
    main:
        banner-mode: 'off'
logging:
    level:
        root: 'off'
my:
    custom:
        value: 'false'
        property: 'costam'
app:
    environment: 'qa'