spring:
    application:
        name: MovieDB
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/MovieDB
        username: root
        password: -Piferman4
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true